### ISSUE TITLE
Add Tests using Jest

### ISSUE THREAD

**Issue by sibelius** [sibelius/graphql-dataloader-boilerplate#1]

**Comment by minheq** [comment]
This boilerplate looks good :) Are you taking concepts from this talk? https://www.youtube.com/watch?v=etax3aEe2dA

It appears so 👍 Hope to see further development on this

**Comment by sibelius** [comment]
I'm taking some concepts from that talk and some other blog posts and videos as well

feel free to submit a pull request
or open an issue with a bug or feature request

ping me on twitter if u need any help running this boilerplate
